### ISSUE TITLE
Discrepancies in response with mergegaps query param

### ISSUE THREAD

**Issue by jbienkowski** [EIDA/ws-availability#2]
The discrepancies between query with and without `mergegaps` is caused by the `fusion(params, data, indexes)` in `apps/data_access_layer.py`. Not sure if it's intentional.

http://orfeus-eu.org/fdsnws/availability/1/query?net=NL&sta=FSW1&cha=HHE&start=2021-04-01&end=2021-04-02

http://orfeus-eu.org/fdsnws/availability/1/query?net=NL&sta=FSW1&cha=HHE&start=2021-04-01&end=2021-04-02&mergegaps=0

http://orfeus-eu.org/fdsnws/availability/1/extent?net=NL&sta=FSW1&cha=HHE&start=2021-04-01&end=2021-04-02

**Comment by jbienkowski** [comment]
Closing - this seems to be related to overlaps in data.

**Comment by petrrr** [comment]
@jbienkowski:

Non sure this behaviour really makes sense. If `mergegaps=0` is considered the default, the output of the two queries should not really be different. 

Should we reopen here?
