### ISSUE TITLE
POST requests blank locations

### ISSUE THREAD

**Issue by vpet98** [EIDA/ws-availability#28]
Hello,

It seems that stations with blank location codes cannot be retrieved using "--" for the location in file for making a POST request, as the FDSN availability specifications indicate. For exampe:
```
http eida.gein.noa.gr/fdsnws/availability/1/query <<< "HL ATH -- * 2023-12-10 2023-12-20"
```
The above line returns nothing, while the below does return results showing a blank location code:
```
http eida.gein.noa.gr/fdsnws/availability/1/query <<< "HL ATH * * 2023-12-10 2023-12-20"
```

**Comment by sheimers** [comment]
We had the same issue, and it is now fixed in the [bugfix-emptyloc](https://github.com/EIDA/ws-availability/compare/bugfix-emptyloc) branch. 

It is very simple,. line 197 in wfcatalog_client.py:



```
if loc == '--':
            loc = ''
```

I'll create a pull request to get it into the master branch.

**Comment by sheimers** [comment]
Now the fix is in the master branch, I will close this issue.
