### ISSUE TITLE
POST requests order of parameters

### ISSUE THREAD

**Issue by vpet98** [EIDA/ws-availability#29]
It seems that the order of the parameters defined in a file for POST request affects the behavior of the webservice.

Below mergegaps option is ignored:
```
http eida.gein.noa.gr/fdsnws/availability/1/query <<< $'format=geocsv\nmergegaps=1.0\nHL ATH * HHE 2023-12-10 2023-12-20'
```

Below both quality and format options are ignored, but mergegaps works:
```
http eida.gein.noa.gr/fdsnws/availability/1/query <<< $'mergegaps=1.0\nquality=R\nformat=geocsv\nHL ATH * HHE 2023-12-10 2023-12-20'
```

Below all parameters work fine:
```
http eida.gein.noa.gr/fdsnws/availability/1/query <<< $'quality=D\nmergegaps=1.0\nformat=geocsv\nHL ATH * HHE 2023-12-10 2023-12-20'
```

**Comment by sheimers** [comment]
We had the same issue, and it is now fixed in the [bugfix-emptyloc](https://github.com/EIDA/ws-availability/compare/bugfix-emptyloc) branch. 

It is very simple,. line 197 in wfcatalog_client.py:

```
if loc == '--':
            loc = ''
```

I'll create a pull request to get it into the master branch.
