### ISSUE TITLE
how to update

### ISSUE THREAD

**Issue by megies** [EIDA/ws-availability#37]
Anything else needed to do to update besides?
```shell
git pull
docker start fdsnws-availability-cacher
```

see https://github.com/EIDA/etc/issues/70#issuecomment-2150198874

**Comment by jbienkowski** [comment]
Hi,

I'm closing this issue as it has been answered here:
https://github.com/EIDA/etc/issues/70#issuecomment-2154222960

Cheers,
Jarek
