### ISSUE TITLE
Improve the processing of MongoDB objects

### ISSUE THREAD

**Issue by jbienkowski** [EIDA/ws-availability#6]
Long running queries (`fdsnws/availability/1/query?net=NL` leave zombie gunicorn workers:
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                            
26956 root      20   0  588352 120160   2848 R  42.2  2.4  10:06.21 gunicorn                                           
27037 root      20   0  588440 120456   3280 R  40.9  2.4   9:56.26 gunicorn                                           
27056 root      20   0  588396 120544   3292 R  35.9  2.4   9:52.87 gunicorn                                           
26953 root      20   0  588444 120164   2848 R  35.2  2.4  10:14.11 gunicorn                                           
27028 root      20   0  588400 120356   3288 R  35.2  2.4   9:54.71 gunicorn
```

It seems that the main issue here is related to the sequential processing of almost 4M MongoDB documents. Those documents cannot be directly shipped to the user, they need to be converted to objects expected by upstream classes. Additionally, for each object a restricted status needs to be found in external source (memcache instance). This makes the entire process pretty slow, especially when handling similar requests in parallel.

Reference: https://github.com/EIDA/ws-availability/blob/master/apps/wfcatalog_client.py#L95

Possible solutions:
- Come with an alternative, more efficient way of processing the MongoDB objects
- Parallelize the MongoDB objects handling (might be an improvement only until web service becomes popular / heavily used)
- Make `sta` query parameter mandatory to prevent users from firing generic requests (check with FDSNWS-Availability specs: http://fdsn.org/webservices/fdsnws-availability-1.0.pdf)
- Limit lifespan of gunicorn workers
- Deploy multiple docker instances with HAProxy load balancer

**Comment by jschaeff** [comment]
Other option (derivated from mandatory `sta` parameter):  implement a 413 http response when the query is too large, if this condition is possible to evaluate (count the mongodb documents before actually treating the request ?)

**Comment by jbienkowski** [comment]
I was also thinking about it. To prevent doing a count for each request, it could be checked only for those very generic queries.

**Comment by damb** [comment]
> I was also thinking about it. To prevent doing a count for each request, it could be checked only for those very generic queries.

What properties qualify a query to a *generic query*? Have you thought about this already? While for a large network such as `net=NL` the request may be quite expensive, for a small temporary network the request might be processed within a *reasonable* short time. To conclude, I don't think that it is reasonable to make the `sta` query filter parameter mandatory.

**Comment by damb** [comment]
@kaestli, for clarification:
- The number of segments corresponds to the number of gaps + 1.

>  Thus, for an availability request, you could estimate the size of the response by counting the number of stream days without gaps (or few gaps), and the number of gaps(=~number of segments) for those stream days with many gaps

- Is it really cheaper to determine the number of segments/gaps based on another query in order to decide whether to return a HTTP status code **413** or not? I assume that it is more efficient to process the request straight away once the number of *requested stream days* does not exceed the service's limits.

**Comment by kaestli** [comment]
on 1:
if n is the number of stream days, and m the number of days with gaps (thus m-n = number of days without gaps, i.e. days with 1 segment), then
total number of segments = (n-m) + (sum<sub>1...m</sub>(GapsOfThisDay+1)  = n-m+m + sumOfGaps
(i think)

on 2:
it depends on the quality of data. Typically you have stations with good communication, or efficient gap backfilling, there you have no gaps, or just a few in case of a major station or power breakdown etc. If you have stations with shaky communication and no gapfilling; there you may easily have 100s of gaps per day. 
If you have one or few of these stations in the dataset of interest, the response size estimation based on the number of stream days may be considerably wrong, and the segments query may return late or never. Now, if there are only few stations in your database, this risk may be acceptable, and you may decide to skip gap-counting. (however, in those cases, gap counting would be cheap anyway as there is little to count)
Whether or not it is worth doing it depends also on your ingestion strategy: As creation of wfcatalog information is very expensive for gappy days, there is a wfcatalog config parameter to tell the system to drop a day from analysis if the processing of a file takes longer than a defined timespan. If you are aware of the share of gappy streams/days in your repo, and of this processing limitation for gappy days, this may help you to decide whether it is worth investing in counting segments for availability requests.
